spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jmx:
server:
  port: 8099
springfox.documentation.swagger.v2.path: /api-docs




